### ISSUE TITLE
Stack command should block until container is created

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator-archive/amp#359] opened 2016-10-20 20:11 UTC
Stack and Stats commands seem to be blocked sometimes, giving varied outputs each time they are executed. Sometimes, these commands run giving the desired output (without any errors). But at times, stack creation using _up_ command fails, which then hinders the execution of other stack commands and stats and/or logs command for stacks.

**Comment by freignat91** [comment] 2016-10-24 05:12
About stats:
Never see stats blocked. Please indicate the way to reproduce it.
Most of the time, we got stats tests error indicating there is no stats published, 
"Unexpected empty answer from server"
Then verify using Grafana that you well have stats in InfluxDB

**Comment by freignat91** [comment] 2016-10-24 07:15
Last tests shows that we we have a race condition between networks and services deletion.
If we just remove the services creation/deletion code, letting all the others action (ETCD storage, networks creation/deletion) than we don't get docker freeze anymore.
Networks creation/deletion are not enough by-itself to freeze Docker.

**Comment by freignat91** [comment] 2016-10-24 12:52
After some tests on services, the issue is related to service stop when services are attached to several networks. Trying to stop in // several service attached to several networks generate a race condition making docker freeze.
Temporary solution to wait for Docker fix:  Stopped one by one services being sure that a service is really stopped, before trying to stop another one. Doing this we get no docker freeze. (tested with 100 stack start/stop using stack test).
Be sure that a service is really stopped is not trivial. I have tested sevaral way which won't success that services is really stopped:
- try to list it using doker api ServiceList until it become not possible
- try to inspect it using docker api ServiceInspectWithRaw until it becomes not possible
- try to list its tacks using TaskList and service name filter until all stacks are gone
All the tries success to show that the service is stopped, but not enough to be sure that the service containers are well detached from the networks and be able to remove to next service
So temporary solution just wait for a while after each service remove.

**Comment by ndegory** [comment] 2016-10-24 13:03
@freignat91 were you able to find an open issue on Docker about this?

**Comment by freignat91** [comment] 2016-10-24 15:54
@ndegory, yes, it's the same docker issue we are on it since 1.12.2

**Comment by freignat91** [comment] 2016-10-24 15:57
After some tests, it appears that the issue is also related to service start when they are attached to several networks. Start/Stop have the same effect if we don't wait service is started or stop one by one. 
Solution: wait for services tacks have desired and running state and with their number equal to the expected replicas.

**Comment by freignat91** [comment] 2016-10-24 15:58
test on going for 100 test loops.

**Comment by freignat91** [comment] 2016-10-25 07:30
Test for 100 stacks test loops done on Ubuntu without docker freeze.
For the moment, etcd doesn't work on mac, I can't execute stack test

**Comment by freignat91** [comment] 2016-10-25 09:10
About stacks:
Related to #344
About docker handing related to stacks start/stop, after tests and study, conclusion:
Docker hang is due to race condition on services networks attachment/detachment
In order to avoid docker hang waiting for a true docker fix (1.12.3 we guess), it's possible to:
- start stack services waiting for a service is fully created (all its containers attached) before trying to start another service (in order to avoid // attachment on networks, especially when several networks are attached)
- remove stack service waiting for a service is fully deleted (all its containers detached) before trying to remove another service (in order to avoid // detachment on networks, especially when several networks are detached)
- do not remove networks, re-use them

Fix has be done integrating these changes, then we got no docker hang even after stack test executed 100 times, on Ubuntu and on OS/X

By the way, this fix answer to this issue request, a stack up command line returns only when all the containers of all its services are running or return an error and on stop command returns when all services are well stopped.

**Comment by freignat91** [comment] 2016-11-02 08:56
Fixed by Docker 1.12.3 and PR#389

**Closed as completed by freignat91** 2016-11-02 08:56 UTC
Labels: kind/bug, area/stack
