### ISSUE TITLE
Getting grpc error when running in docker toolbox on windows

### ISSUE THREAD

**Issue by davidrmckenna** [appcelerator-archive/amp#1400] opened 2017-06-19 13:10 UTC
**Description**
After I initially extract AMP and attempt to run it in Docker Toolbox on Windows 7 (64bit) I'm getting a grpc error when it attempts to get the server version of AMP

**Steps to reproduce the issue:**
1. Download AMP from here: https://get.atomiq.io/builds/Windows/x86_64/amp-v0.11.0.zip
2. Attempt to run the command: 
`./amp --server localhost version`
3. grpc error is noted (see error below)
4. Run the command:
`amp -s localhost cluster create`

Get the output:
```
Cluster status: healthy
zb3v6ovm8u0y4uslni0af14sb
```

5. Attempt to run the command: 
./amp --server localhost version
6. Error below noted again

**Results you received:**

```
dmckenna@ITEM-AX43897 MINGW64 ~/workspace
$ ./amp --server localhost version
[localhost:50101]
grpc: addrConn.resetTransport failed to create client transport: [connection err
or: desc = "transport: dial tcp [::1]:50101: operation was canceled" {localhost:
50101 <nil>}]; Reconnecting to %!v(MISSING)
Client:
 Version:       v0.11.0
 Build:         f7e0520e
 Server:        localhost:50101
 Go version:    go1.8.1
 OS/Arch:       windows/amd64

Server:         not connected
```

**Comment by ingo** [comment] 2017-06-19 13:17
Seems related to #968

**Comment by ingo** [comment] 2017-06-19 13:20
I also get this on Mac:

Moxie-3:Downloads ingo$ amp version -s localhost
[localhost:50101]
Client:
 Version:       v0.11.0
 Build:         f7e0520e
 Server:        localhost:50101
 Go version:    go1.8.1
 OS/Arch:       darwin/amd64

Server:         
 Version:       v0.11.0
 Build:         f7e0520e
 Go version:    go1.8.1
 OS/Arch:       linux/amd64
Moxie-3:Downloads ingo$ amp version
[cloud.appcelerator.io:50101]

grpc: addrConn.resetTransport failed to create client transport: [connection error: desc = "transport: dial tcp 52.35.70.202:50101: operation was canceled" {cloud.appcelerator.io:50101 <nil>}]; Reconnecting to %!v(MISSING)Client:
 Version:       v0.11.0
 Build:         f7e0520e
 Server:        cloud.appcelerator.io:50101
 Go version:    go1.8.1
 OS/Arch:       darwin/amd64

**Comment by alasdairhurst** [comment] 2017-06-19 13:22
Running into the same issue consistently on Windows 10 anniversary update x64. 
(docker but not docker-toolbox)
AMP v0,11.0 and v0.12.0-dev

This error shows when doing
```amp --server localhost version```
but not
```amp --server localhost -v```

It also shows when deploying
```amp -s localhost stack deploy -c pinger.yml pinger```
```
Deploying stack pinger using pinger.yml
transport: http2Client.notifyError got notified that the client transport was broken [read tcp 127.0.0.1:65152->127.0.0.1:50101: wsarecv: An existing connection was forcibly closed by the remote host.].transport: http2Client.notifyError got notified that the client transport was broken [read tcp 127.0.0.1:65153->127.0.0.1:50101: wsarecv: An existing connection was forcibly closed by the remote host.].Error: transport is closing

```

and creating a user
```amp -s localhost user signup```
```
transport: http2Client.notifyError got notified that the client transport was broken [read tcp 127.0.0.1:65074->127.0.0.1:50101: wsarecv: An existing connection was forcibly closed by the remote host.].transport: http2Client.notifyError got notified that the client transport was broken [read tcp 127.0.0.1:65075->127.0.0.1:50101: wsarecv: An existing connection was forcibly closed by the remote host.].transport: http2Client.notifyError got notified that the client transport was broken [read tcp 127.0.0.1:65076->127.0.0.1:50101: wsarecv: An existing connection was forcibly closed by the remote host.].Error: transport: write tcp 127.0.0.1:65076->127.0.0.1:50101: use of closed network connection
```

**Comment by ingo** [comment] 2017-06-19 13:22
It alternates:

Moxie-3:Downloads ingo$ amp version
[cloud.appcelerator.io:50101]

grpc: addrConn.resetTransport failed to create client transport: [connection error: desc = "transport: dial tcp 52.88.251.38:50101: operation was canceled" {cloud.appcelerator.io:50101 <nil>}]; Reconnecting to %!v(MISSING)Client:
 Version:       v0.11.0
 Build:         f7e0520e
 Server:        cloud.appcelerator.io:50101
 Go version:    go1.8.1
 OS/Arch:       darwin/amd64

Server:         not connected
Moxie-3:Downloads ingo$ amp version
[cloud.appcelerator.io:50101]
Client:
 Version:       v0.11.0
 Build:         f7e0520e
 Server:        cloud.appcelerator.io:50101
 Go version:    go1.8.1
 OS/Arch:       darwin/amd64

Server:         
 Version:       v0.12.0-dev
 Build:         036c673c
 Go version:    go1.8.1
 OS/Arch:       linux/amd64
Moxie-3:Downloads ingo$ amp version
[cloud.appcelerator.io:50101]
Error: grpc: Decompressor is not installed for grpc-encoding "gzip"

**Comment by ndegory** [comment] 2017-06-19 13:23
do you experience this issue after 15 min of inactivity, or is it as soon as it is deployed? We've fixed recently an issue related to the VIP timeout, that my be related.

**Comment by davidrmckenna** [comment] 2017-06-19 21:09
I get it after I deploy the cluster. Deploy of cluster concludes with message:

```
dmckenna@ITEM-AX43897 MINGW64 ~/workspace
$ ./amp -s localhost cluster create
[localhost:50101]
wait for cluster
ok
cluster size is 1
deploy amp monitoring stack to cluster - stage 1
deploy ampmon.1.stack.yml => amp
Creating service amp_elasticsearch
Creating service amp_nats
Creating service amp_etcd
ok
wait for all amp monitoring stage 1 stack service replicas to be running
ok
deploy amp monitoring stack to cluster - stage 2
deploy ampmon.2.stack.yml => amp
Creating service amp_ampbeat
Creating service amp_kibana
ok
wait for all amp monitoring stage 2 service replicas to be running (540 sec)
ok
deploy portal stack to cluster
deploy portal.stack.yml => amp
Creating service amp_portal
ok
wait for all portal service replicas to be running (540 sec)
ok
deploy amp stack to cluster
deploy amp.stack.yml => amp
Creating service amp_amplifier
Creating service amp_amplifier-gateway
Creating service amp_agent
ok
wait for all amp service replicas to be running (540 sec)
ok
deploy amp proxy stack to cluster
deploy ampproxy.stack.yml => amp
Creating service amp_proxy
ok
wait for all amp proxy service replicas to be running (540 sec)
ok

Cluster status: healthy
f573e897-7aa0-4516-a195-42ee91039e97
```

**Comment by neha-viswanathan** [comment] 2017-06-27 20:07
@davidrmckenna @ingo @alasdairhurst  apologies for the delayed response.

We don't plan to support Docker Toolbox for Windows for the GA release. You need Docker for Windows instead.
However, we did a bit of investigation with Docker Toolbox for Windows. There are a few adaptations to be made around accessing the deployed stacks, which we have not planned for the GA. Here is what we found:
With the Toolbox, Docker runs inside a VM and not on your machine itself, which is why you got the grpc error on passing `localhost` as the server address. 

The workaround for this is to use the IP of the Docker Machine running on the VM. You can do this by launching Docker Quickstart Terminal and running :
`$ echo $DOCKER_HOST`

Use the IP returned instead of `localhost` for the commands.

**Comment by alasdairhurst** [comment] 2017-06-28 09:29
@neha-viswanathan  While @davidrmckenna is running docker toolbox, I was running Docker for windows (Docker for windows doesn't work on win 7, and docker toolbox doesn't work on win 10)
As you can see, I was getting identical grpc issues.

**Comment by neha-viswanathan** [comment] 2017-06-28 18:16
@alasdairhurst I am unable to reproduce the grpc issue that you are facing with Windows 10. It would be helpful to further investigate if you can open another issue describing the steps to reproduce it.

**Comment by alasdairhurst** [comment] 2017-06-30 10:41
@neha-viswanathan  created #1479

**Comment by neha-viswanathan** [comment] 2017-07-06 17:22
Closing the issue since we do not support Docker Toolbox on any OS.

**Closed as completed by neha-viswanathan** 2017-07-06 17:22 UTC
Labels: kind/bug, toolbox/windows, version/0.11
