### ISSUE TITLE
Integration tests are failing on master branch

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#524] opened 2016-12-06 11:04 UTC
Integration tests are failing because of missing binary in the test image.
CLI tests are also failing for some reason.

Here is an excerpt of the build travis build https://travis-ci.org/appcelerator/amp/builds/181707477 :
```
ok  	github.com/appcelerator/amp/tests/integration/data/influx	0.015s
ok  	github.com/appcelerator/amp/tests/integration/data/storage/etcd	1.137s
# github.com/appcelerator/amp/vendor/github.com/docker/docker/pkg/term
exec: "gcc": executable file not found in $PATH
# github.com/appcelerator/amp/vendor/github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/system
exec: "gcc": executable file not found in $PATH
FAIL	github.com/appcelerator/amp/tests/integration/rpc [build failed]
make: *** [test-integration-host] Error 2
Makefile:200: recipe for target 'test-integration-host' failed
--- FAIL: TestCmds (10.45s)
	cli_test.go:65: -----------------------------------------------------------------------------------------
	cli_test.go:67: Running spec: samples/logs.yml
	cli_test.go:67: Running spec: samples/service.yml
	cli_test.go:67: Running spec: samples/stack.yml
	cli_test.go:67: Running spec: samples/stats.yml
	cli_test.go:120: Running: amp service create appcelerator/pinger --name pingerABHmUnLUtm -p www:55915:3000
	cli_test.go:120: Running: docker service ls
	cli_test.go:120: Running: curl localhost:55915/ping
	cli_test.go:133: Mismatched expected output:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
		                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 55915: Connection refused
		 : Error: exit status 7
	cli_test.go:120: Running: amp stack up stack1yZouCyQgUP -f ../../api/rpc/stack/test_samples/sample-01.yml
	cli_test.go:120: Running: amp logs
	cli_test.go:120: Running: amp stats --container
	cli_test.go:120: Running: amp stack ls
	cli_test.go:120: Running: amp stack stop stack1yZouCyQgUP
	cli_test.go:120: Running: amp logs -m
	cli_test.go:120: Running: amp stats --cpu
	cli_test.go:133: Mismatched expected output: Error during: amp stats, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:154: Mismatched expected output: Error during: amp stats, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:155: 
	cli_test.go:120: Running: amp logs -n 10
	cli_test.go:120: Running: amp stack ls
	cli_test.go:133: Mismatched expected output: Error during: amp ls, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:154: Mismatched expected output: Error during: amp ls, reason: rpc error: code = 13 desc = transport is closing
		 : Error: exit status 1
	cli_test.go:155: 
	cli_test.go:120: Running: curl localhost:55915/ping
	context.go:22: Deadline exceeded: amp stats
	context.go:22: Deadline exceeded: amp stack ls
	context.go:22: Deadline exceeded: amp logs
	context.go:22: Deadline exceeded: amp service rm
	cli_test.go:120: Running: amp service rm pingerABHmUnLUtm
	cli_test.go:120: Running: docker service ls
	cli_test.go:120: Running: amp logs --stack stack1
	cli_test.go:71: -----------------------------------------------------------------------------------------
	cli_test.go:72: Finished!
FAIL
FAIL	github.com/appcelerator/amp/tests/cli	10.453s
make: *** [test-cli] Error 1
The command "make test" exited with 2.
Done. Your build exited with 1.
```

**Comment by JosephGJ** [comment] 2016-12-06 19:30
After running `make test` on the master, I get the following return. The cli tests consistently pass and they very rarely fail. I can replicate the issue you are having.
```
ok      github.com/appcelerator/amp/tests/integration/data/influx       0.009s
ok      github.com/appcelerator/amp/tests/integration/data/storage/etcd 1.295s
# github.com/appcelerator/amp/vendor/github.com/docker/docker/pkg/term
exec: "gcc": executable file not found in $PATH
# github.com/appcelerator/amp/vendor/github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/system
exec: "gcc": executable file not found in $PATH
FAIL    github.com/appcelerator/amp/tests/integration/rpc [build failed]
Makefile:200: recipe for target 'test-integration-host' failed
make: *** [test-integration-host] Error 2
ok      github.com/appcelerator/amp/tests/cli   7.594s
```

After adding the changes from PR #525, `make test`will pass.
```
ok      github.com/appcelerator/amp/tests/integration/data/influx       0.016s
ok      github.com/appcelerator/amp/tests/integration/data/storage/etcd 1.286s
ok      github.com/appcelerator/amp/tests/integration/rpc       37.214s
ok      github.com/appcelerator/amp/tests/cli   6.309s
```
As suggested in your message, I will work on making the cli_test.go logs less chatty and make any errors that occur easier to identify and diagnose, along with making the command timeouts more forgiving.

**Comment by bquenin** [comment] 2016-12-06 21:05
@JosephGJ you're right, the PR #525 fixes the `gcc` issue. However, when I was working on this PR, the CLI tests kept failing on travis.
This is mostly a travis CI issue as CLI tests are working most of the time locally.
If you look at the `fix-integration-tests` branch build history on travis here: https://travis-ci.org/appcelerator/amp/branches, you will see that tests never passed despite several attempts, so I finally closed the PR.
Do you want me to reopen it so that you can work on it or do you want to work on your own PR ?

Just let me know

**Comment by JosephGJ** [comment] 2016-12-06 21:33
Bertrand, I'll open a PR and I'll work on the Cli changes that I've mentioned above on said PR. I'll take the changes you made to the makefile and docker.test file and put them on there.

I rebuilt the travis build and it passed, however, I think this `rpc error: code = 13 desc = transport is closing` error is worth looking into.

The cli tests can be somewhat random as described because of the commands that are being tested are unstable, and being able to identify this is primary purpose of these tests.

**Comment by bquenin** [comment] 2016-12-07 01:02
Ok, thanks!
You're right, maybe there's a real issue lurking, it would be great to be able to reproduce the issue in a deterministic way in order to fix it.

**Comment by JosephGJ** [comment] 2016-12-08 00:34
The error you've been experiencing bertrand has persisted even with the minor changes. You can see this referenced in #529.

I think the issue is that amplifier is crashing during the execution of `make test`. Taking a look at the amplifier logs may show us the source of the problem.

**Closed as completed** 2016-12-08 16:13 UTC
Labels: kind/bug, priority/P0, area/test
